# Generated by Django 4.2.1 on 2023-06-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('hash', models.CharField(max_length=255)),
                ('hash_method', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('ctime', models.BigIntegerField()),
                ('mtime', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('transformers', 'Transformers'), ('openai', 'Openai')], max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('num_dimensions', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffsetConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offset_type', models.CharField(choices=[('chunks', 'Chunks')], max_length=255)),
                ('offset_size', models.IntegerField()),
                ('overlap_size', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PdfConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.file')),
                ('file_type', models.CharField(choices=[('pdf', 'Pdf'), ('csv', 'Csv'), ('txt', 'Text')], max_length=255)),
            ],
            bases=('db.file',),
        ),
        migrations.CreateModel(
            name='TokenTransform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_tokens', models.IntegerField()),
                ('input_text_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.file')),
                ('model_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.modelconfig')),
                ('output_token_json_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.file')),
            ],
        ),
        migrations.CreateModel(
            name='PdfTransform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_pages', models.IntegerField()),
                ('input_pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.file')),
                ('output_page_position_json_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.file')),
                ('output_txt_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.file')),
                ('pdf_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.pdfconfig')),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingTransform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_embeddings', models.IntegerField()),
                ('output_embeddings_doc_id', models.CharField(max_length=255)),
                ('input_tokens_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.file')),
                ('model_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.modelconfig')),
                ('offset_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.offsetconfig')),
                ('output_offsets_json_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.file')),
            ],
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('contentfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.contentfile')),
                ('page_map', models.JSONField()),
            ],
            bases=('db.contentfile',),
        ),
        migrations.AddConstraint(
            model_name='tokentransform',
            constraint=models.UniqueConstraint(fields=('input_text_file', 'model_loader'), name='unique_token_transform'),
        ),
        migrations.AddConstraint(
            model_name='pdftransform',
            constraint=models.UniqueConstraint(fields=('input_pdf_file', 'pdf_loader'), name='unique_pdf_file_loader'),
        ),
        migrations.AddConstraint(
            model_name='embeddingtransform',
            constraint=models.UniqueConstraint(fields=('input_tokens_file', 'model_loader', 'offset_loader'), name='unique_embedding_transform'),
        ),
    ]
